name: restoku
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.2
  http: ^0.13.4
  supabase_flutter: ^2.8.2
  dropdown_search: ^5.0.6
  url_launcher: ^6.0.20
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Tambahkan paket ini di dev_dependencies

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    -  assets/estehajib.jpeg
    - assets/japanesepancake.jpg
    - assets/lemonade.jpg
    - assets/logo.jpg
    - assets/beef-salad.jpg
    - assets/coffee.jpg
    - assets/korean-strawberry-milk.jpg
    - assets/manggo-pancake.jpg
    - assets/orange-sunset.jpg
    - assets/salmon-sushi.jpg
    - assets/salted-egg-ramen.jpg
    - assets/sparkling-winter.jpg
    - assets/steak.jpg