// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClQrMocegAK6n4K-cVSyJOvGJ4o4KST90',
    appId: '1:726137725939:web:0b835c8aaee62ca90f6886',
    messagingSenderId: '726137725939',
    projectId: 'restoku-ca7f1',
    authDomain: 'restoku-ca7f1.firebaseapp.com',
    storageBucket: 'restoku-ca7f1.firebasestorage.app',
    measurementId: 'G-9NYK741VTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTyu-F9Wh4FEBcRFZAqgodrIbU5emti8',
    appId: '1:726137725939:android:00136f898c16fef60f6886',
    messagingSenderId: '726137725939',
    projectId: 'restoku-ca7f1',
    storageBucket: 'restoku-ca7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXCInT0Ku8hLFF5G5yeH8aTZ_AljXtVc',
    appId: '1:726137725939:ios:b556d2db61dd26ee0f6886',
    messagingSenderId: '726137725939',
    projectId: 'restoku-ca7f1',
    storageBucket: 'restoku-ca7f1.firebasestorage.app',
    iosBundleId: 'com.example.restoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfXCInT0Ku8hLFF5G5yeH8aTZ_AljXtVc',
    appId: '1:726137725939:ios:b556d2db61dd26ee0f6886',
    messagingSenderId: '726137725939',
    projectId: 'restoku-ca7f1',
    storageBucket: 'restoku-ca7f1.firebasestorage.app',
    iosBundleId: 'com.example.restoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClQrMocegAK6n4K-cVSyJOvGJ4o4KST90',
    appId: '1:726137725939:web:6ae884f5cffde1830f6886',
    messagingSenderId: '726137725939',
    projectId: 'restoku-ca7f1',
    authDomain: 'restoku-ca7f1.firebaseapp.com',
    storageBucket: 'restoku-ca7f1.firebasestorage.app',
    measurementId: 'G-RJRVJ6XPQX',
  );
}
